Preaparación de los datos

In [35]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
X = iris.data[:,[2,3]]
y = iris.target

Entrenamiento

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 1, stratify = y)

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

1. Regresión logística

In [38]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=100.0, random_state = 1, solver = 'lbfgs', multi_class='ovr')
lr.fit(X_train_std, y_train)
# Predicciones
y_pred = lr.predict(X_test_std)
y_pred

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0])

serialización

In [39]:
import pickle

with open('../models/logistic_regression.pck', 'wb') as f:
    pickle.dump((sc, lr), f)

2. Support Vector Machine

In [40]:
from sklearn.svm import SVC

svm = SVC(kernel='linear',C=1.0, random_state=1)
svm.fit(X_train_std, y_train)
# Predicciones
y_pred = svm.predict(X_test_std)
y_pred

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0])

serialización

In [41]:
with open('../models/svm.pck', 'wb') as f:
    pickle.dump((sc, svm), f)

3. Decision Tree

In [42]:
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier(criterion='gini',max_depth=4, random_state=1)
tree_model.fit(X_train,y_train)
# Predicciones
y_pred = tree_model.predict(X_test)
y_pred

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0])

serialización

In [43]:
with open('../models/decision_tree.pck', 'wb') as f:
    pickle.dump((sc, tree_model), f)

4. K-Nearest Neighbours

In [44]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3, p=2, metric='minkowski')
knn.fit(X_train_std, y_train)
# Predicciones
y_pred = knn.predict(X_test_std)
y_pred

array([2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 0,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0,
       0])

serialización

In [45]:
with open('../models/knn.pck', 'wb') as f:
    pickle.dump((sc, knn), f)